name: Push Action

on:
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
  
      - name: install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: | 
          npm run lint
          npm run test
          npm run build

      - name: Deploy application
        run: echo "Deploying application..."
